
version: '3'

services:
  speedtest:
    image: ubuntu:latest
    command: >
          bash -c "\
            # Set up directories
            mkdir -p /mnt/data && \ 
            mkdir -p /var/log/cron && \
            export DEBIAN_FRONTEND=noninteractive && \
            
            # Install depedencies
            apt-get update && \
            apt-get install -y --no-install-recommends vim speedtest-cli cron tzdata moreutils && \
            ln -fs /usr/share/zoneinfo/Europe/Luxembourg /etc/localtime && \            
          
            # Init the CSV file
            echo 'if [[ ! -f /mnt/data/speed.csv ]]; then speedtest --csv-header > /mnt/data/speed.csv; fi' > /usr/local/bin/init_csv.sh && \
            chmod +x /usr/local/bin/init_csv.sh && \            
            /usr/local/bin/init_csv.sh && \
            
            # Creating the speedtest scripts
            # Redirecting stderr 2> to stdout 1> and stdout 1> to 3>
            # Then appending timestamp only to 2>
            # Redirecting 3> to stdout
            echo '{ speedtest --csv --share 2>&1 1>&3 | ts >> /mnt/data/speed.err; } 3>> /mnt/data/speed.csv' > /usr/local/bin/run_speedtest.sh && \
            chmod +x /usr/local/bin/run_speedtest.sh && \
            /usr/local/bin/run_speedtest.sh && \
  
            
            # Scheduling the cron job
            # Note: cron jobs scheduled at HH:00 would fail from speedtest.
            # Note: For some reason, the cron daemon doesn't execute 10 minutes intervals
            #       when using */10. Workaround is to enumerate the minutes.
            echo '2,12,22,32,42,52 * * * * root /bin/bash /usr/local/bin/run_speedtest.sh' > /etc/cron.d/speedtest-cron && \
            echo '0 0 * * 0 apt-get update && apt-get install -y --no-install-recommends speedtest-cli' > /etc/cron.d/weekly-update && \                                                
            cron -f"
            
    volumes:
      - /share/CACHEDEV1_DATA/Public/:/mnt/data
    networks:
      - qnet-dhcp-eth1-6d6da6

networks:
  qnet-dhcp-eth1-6d6da6:
    external: true