version: '3'
name: grafana

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana            
    volumes:
      - /share/CACHEDEV1_DATA/Public/:/mnt/public
    ports:
      - 3000:3000
    networks:
      #- qnet-dhcp-eth1-6d6da6
      - grafana
           
    restart: always
    command: >
          bash -c "\
            # Installing plugins            
            grafana cli plugins install yesoreyeram-infinity-datasource  && \
            grafana cli plugins install marcusolsson-csv-datasource  && \
            # Enable local mode
            echo '[plugin.marcusolsson-csv-datasource]' >> /etc/grafana/grafana.ini && \
            echo 'allow_local_mode = true' >> /etc/grafana/grafana.ini  && \

            # Note: the container needs to restart after installing new plugins
            echo 'Rebooting to enable the newly installed plugins' && \
            reboot"

networks:
  #qnet-dhcp-eth1-6d6da6:
  grafana:
    #external: true
    driver: bridge