version: '3'
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      - TZ=Europe/XXX
      - DNS1=8.8.8.8
      - DNS2=8.8.4.4
      - DNSMASQ_USER=root
      - PIHOLE_UID=1000
      - PIHOLE_GID=0
      - WEBPASSWORD=XXXXX
      - SERVERIP=XXXX # The IP of the NAS
    volumes:
      - '/share/CACHEDEV1_DATA/Container/pihole/etc-pihole:/etc/pihole'
      - '/share/CACHEDEV1_DATA/Container/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      qnet-static-eth1-b03c93:
        ipv4_address: XXXX # The IP of the Pihole container

networks:
  qnet-static-eth1-b03c93:
    external: true