
version: '3'

services:
  speedtest:
    image: ubuntu:latest
    command: >
          bash -c "\
            # Set up directories
            mkdir -p /mnt/data && \ 
            mkdir -p /var/log/cron && \
            export DEBIAN_FRONTEND=noninteractive && \
            
            #echo \"if [[ ! -f '/mnt/data/speed.csv' ]] then; echo 'Timestamp,Ping,Download,Upload' > /mnt/data/speed.csv\nfi\" > /usr/local/bin/init_csv.sh && \
            echo 'if [[ ! -f /mnt/data/speed.csv ]]; then echo \"Timestamp,Ping,Download,Upload\" > /mnt/data/speed.csv; fi' > /usr/local/bin/init_csv.sh && \
            chmod +x /usr/local/bin/init_csv.sh && \            
            /usr/local/bin/init_csv.sh && \
            
            # Creating the speedtest scripts
            # Redirecting stderr 2> to stdout 1> and stdout 1> to 3>
            # Then appending timestamp only to 2>
            # Redirecting 3> to stdout
            echo '{ speedtest --csv 2>&1 1>&3 | ts >> /mnt/data/speed.err | cut -d \",\" -f 4,6,7,8,3; } 3>> /mnt/data/speed.csv' > /usr/local/bin/run_speedtest.sh && \
            chmod +x /usr/local/bin/run_speedtest.sh && \
            /usr/local/bin/run_speedtest.sh && \
  
            # Install depedencies
            apt-get update && \
            apt-get install -y --no-install-recommends vim speedtest-cli jq cron tzdata moreutils && \
            ln -fs /usr/share/zoneinfo/Europe/Luxembourg /etc/localtime && \            
          
            # Scheduling the cron job
            # cron jobs scheduled at HH:00 would fail from speedtest.
            echo '*/10 * * * * root /bin/bash /usr/local/bin/run_speedtest.sh' > /etc/cron.d/speedtest-cron && \
            echo '0 0 * * 0 apt-get update && apt-get install -y --no-install-recommends speedtest-cli jq' > /etc/cron.d/weekly-update && \                                                
            cron -f"
            
    volumes:
      - /share/CACHEDEV1_DATA/Public/:/mnt/data
    networks:
      - qnet-dhcp-eth1-6d6da6

networks:
  qnet-dhcp-eth1-6d6da6:
    external: true